# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simplificator-fsm}
  s.version = "0.3.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["simplificator"]
  s.date = %q{2011-10-24}
  s.email = %q{info@simplificator.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION.yml",
    "fsm.gemspec",
    "lib/fsm.rb",
    "lib/fsm/builder.rb",
    "lib/fsm/dot.rb",
    "lib/fsm/errors.rb",
    "lib/fsm/executable.rb",
    "lib/fsm/machine.rb",
    "lib/fsm/options.rb",
    "lib/fsm/state.rb",
    "lib/fsm/state_attribute_interceptor.rb",
    "lib/fsm/transition.rb",
    "samples/ticket/ticket.png",
    "samples/ticket/ticket.ps",
    "samples/ticket/ticket_sample.rb",
    "simplificator-fsm.gemspec",
    "test/ar_test.rb",
    "test/executable_test.rb",
    "test/invoice_sample_test.rb",
    "test/options_test.rb",
    "test/state_test.rb",
    "test/test_helper.rb",
    "test/test_helper_ar.rb",
    "test/transition_test.rb",
    "test/water_sample_test.rb"
  ]
  s.homepage = %q{http://github.com/simplificator/fsm}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A simple finite state machine (FSM) gem.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

